jaffle_shop:

  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: dataops-m2i
      dataset: "{{ env_var('OWNER') }}"
      job_execution_timeout_seconds: 15000
      job_retries: 1
      priority: interactive
      threads: 4
